# Uncomment this line to define a global platform for your project
platform :ios, "6.0"

target "MAInfo" do
platform :ios, '6.0'
pod 'SLExpandableTableView'
pod 'OCMock', '>= 2.2'
  pod 'Expecta', '>= 0.2.2'
  pod 'KIF', '~> 2.0'
end

target "MAInfoTests" do

end

